### ISSUE TITLE
データ更新ができない

### ISSUE THREAD

**Issue by LAC-Ikeda** [covid19-kitakyushu/covid19#1429]
## 起こっている問題 / The Problem
- 以下の箇所でエラーが発生

## スクリーンショット / Screenshot
`(node:2427) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '民間検査機関検査実施_件数' of undefined
    at getInspectionBreakdown (/Users/ikedahiroki/covid19-data-updater/main.js:453:36)
    at main (/Users/ikedahiroki/covid19-data-updater/main.js:508:16)
    at async t (/Users/ikedahiroki/covid19-data-updater/main.js:551:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2427) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2427) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by LAC-Ikeda** [comment]
covid19-data-updaterに移動
